services:
  postgres:
    image: postgres:16-alpine
    container_name: piano-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: piano_db
      POSTGRES_USER: piano
      POSTGRES_PASSWORD: piano1234
    volumes:
      - piano-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: piano-redis
    ports:
      - "6379:6379"
    volumes:
      - piano-redis-data:/data

volumes:
  piano-postgres-data:
  piano-redis-data:
